### ISSUE TITLE
[Suggestion]: Align intro with challenges for 04

### ISSUE THREAD

**Issue by softcraftsman** [onemtc/wth-fork#26]
### Which Hack?

045-InfraAsCode-Bicep

### Suggestion

Challenge 4 intro describes deploying a VM, but in this one we are deploying a Key Vault which is used in Challenge 5 for VM creation.  I would change this description to be about reading secret values from a Key Vault.

I would also change the challenge section to break out the key vault creation into a 'setup' section that the students can blindly run.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by larryclaman** [comment]
fixed
